# use -u flag or env PYTHONUNBUFFERED=1  to allow console logs to appear instantly (instead of being buffered)
version: '3'

services:
  ftp-puller:
    image: davis8988/ftp-puller:python-3.7.2-slim
    container_name: ftp-puller
    user: 'root'
    volumes:
      - /opt/sources/ftp-file-puller-git:/home/ftp
    environment:
      - FTP_ADDRESS=ftp.elbitsystems.com
      - FTP_USER=dp99662
      - FTP_PASSWORD=gAAAAABfEdFmzeDxO2M_1Dn4dtu9b7vdRPnWcaYYgJAQ30Wa-cqEo6Bsmn5-fKosb4_kmxo1bI7KWuRYN-VyhK_nMmWW-xZVvg==
      - FTP_ENCRYPT_KEY=9PTLf_k100EtQTHMgCNoE7ac0dq8p0RwTzVJkjHG9wo=
      - FTP_SOURCE_PATH=/Yokneam/Scripts/Stream
      - FTP_DEST_PATH=/home/ftp
      - CRONTAB_TIME=* * * * *
    ports:
      - 21:21
    command: "python -u /root/ftp-files-puller.py --verbose --hashed --remove_src --setup_as_crontab_job "


