# For starting ftp-puller
version: '3'

services:
  ftp-puller:
    image: davis8988/ftp-puller:python-3.7.2-slim
    container_name: ftp-puller
    user: 'root'
    volumes:
      - /opt/sources/ftp-file-puller-git:/home/ftp
    environment:
      - FTP_ADDRESS=ftp.elbitsystems.com
      - FTP_USER=dp99662
      - FTP_PASSWORD=gAAAAABdg4_xDNvtquLIZ3wVy1UyzmJ7-1XbYh9qDJ6WqngKo78mdSnvNyYX-68nsWSmzT7Y6Pu03_PZgbzEmuLcdeqFedQ3nA==
      - FTP_ENCRYPT_KEY=9PTLf_k100EtQTHMgCNoE7ac0dq8p0RwTzVJkjHG9wo=
      - FTP_SOURCE_PATH=/Yokneam/Scripts/Stream
      - FTP_DEST_PATH=/home/ftp
    ports:
      - 21:21
    command: "python /root/ftp-files-puller.py --hashed --remove_src --very_verbose --setup_as_crontab_job --crontab_time='* * * * *' "


